name: node-be
app: node

options:
  env:
    - name: DB_HOST
      value: svc.sel4.cloudtype.app
    - name: DB_PORT
      value: 31874
    - name: DB_USER
      value: master
    - name: DB_PASSWORD
      value: 0213
    - name: DB_NAME
      value: chat
  ports: 3007
  install: npm install
  start: node index.js